# Generated by Django 5.2 on 2025-07-01 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cotización / Pedido', 'verbose_name_plural': 'Cotizaciones / Pedidos'},
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_document',
            field=models.CharField(blank=True, max_length=30, verbose_name='Documento del Cliente (invitado)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente (invitado)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del Cliente (invitado)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del Cliente (invitado)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrado (Opcional)'),
        ),
    ]
