# Generated by Django 5.2 on 2025-09-20 04:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_quote_options_quote_customer_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('valid_from', models.DateTimeField(verbose_name='Válido desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido hasta')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], max_length=15, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Si es porcentaje, 10.00 para 10%. Si es fijo, el monto.', max_digits=10, verbose_name='Valor del Descuento')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Para descuentos de porcentaje, el monto máximo a descontar.', max_digits=10, null=True, verbose_name='Monto Máximo de Descuento')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Mínimo de Compra')),
                ('uses_limit', models.PositiveIntegerField(default=1, help_text='Número total de veces que se puede usar el cupón.', verbose_name='Límite de Usos')),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Usos Actuales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-valid_to'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento por Cupón'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_document',
            field=models.CharField(blank=True, max_length=30, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='carts.coupon', verbose_name='Cupón'),
        ),
        migrations.AddField(
            model_name='quote',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_used', to='carts.coupon', verbose_name='Cupón Aplicado'),
        ),
    ]
