# Generated by Django 5.2 on 2026-06-08 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_coupon_quote_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Si es porcentaje, 10.00 para 10%. Si es fijo, el monto.', max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para descuentos de porcentaje, el monto máximo a descontar.', max_digits=10, null=True, verbose_name='Máx Desc'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Compra Mín'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='uses_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='uses_limit',
            field=models.PositiveIntegerField(default=1, help_text='Número total de veces que se puede usar el cupón.', verbose_name='Total Usos'),
        ),
    ]
