# Generated by Django 5.2 on 2026-06-08 23:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='cost_at_quote',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
