# Generated by Django 5.2 on 2026-06-08 23:24

from django.db import migrations

from decimal import Decimal

def populate_cost_at_quote(apps, schema_editor):
    QuoteItem = apps.get_model('carts', 'QuoteItem')
    for item in QuoteItem.objects.all():
        if item.product and hasattr(item.product, 'purchase_price') and item.product.purchase_price:
            item.cost_at_quote = item.product.purchase_price
            item.save()

def reverse_populate_cost_at_quote(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_quoteitem_cost_at_quote'),
        ('products', '0009_auto_20260608_2319'),
    ]

    operations = [
        migrations.RunPython(populate_cost_at_quote, reverse_populate_cost_at_quote),
    ]
