# Generated by Django 5.2 on 2026-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20260608_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('backorder_paid', 'Bajo Pedido (Pagado)'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
