# Generated by Django 5.2 on 2025-05-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Banner (interno)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagen del Banner')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto Alternativo (SEO y Accesibilidad)')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='URL de Destino (opcional)')),
                ('placement', models.CharField(choices=[('home_main', 'Home - Carrusel Principal'), ('home_secondary', 'Home - Sección Secundaria'), ('product_list_top', 'Listado de Productos - Superior'), ('product_list_sidebar', 'Listado de Productos - Barra Lateral'), ('product_detail_related', 'Detalle de Producto - Relacionados'), ('general_sitewide_top', 'General - Encabezado Sitio')], db_index=True, max_length=50, verbose_name='Ubicación del Banner')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número se muestra primero en la misma ubicación.', verbose_name='Orden de Visualización')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio (opcional)')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['placement', 'order', 'name'],
            },
        ),
    ]
