# Generated by Django 5.2 on 2025-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, help_text='Marcar si esto es un servicio y no un producto físico. No será visible para clientes en la tienda.', verbose_name='Es un Servicio'),
        ),
    ]
