# Generated by Django 5.2 on 2026-06-08 23:19

from django.db import migrations

from decimal import Decimal

def populate_average_cost(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.purchase_price:
            product.average_cost = product.purchase_price
            product.save()

def reverse_populate_average_cost(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_average_cost'),
    ]

    operations = [
        migrations.RunPython(populate_average_cost, reverse_populate_average_cost),
    ]
