# Generated by Django 5.2 on 2026-06-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_brand_supplier_product_brand_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_cop_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo en pesos colombianos. Se calcula automáticamente o se puede editar manual.', max_digits=12, null=True, verbose_name='Costo COP (Referencia)'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference_usd_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo en dólares. Solo para uso interno.', max_digits=10, null=True, verbose_name='Costo USD (Referencia)'),
        ),
    ]
