# Generated by Django 5.2 on 2026-06-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_reference_cop_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
            ],
            options={
                'verbose_name': 'Gestión de Precios y Stock',
                'verbose_name_plural': 'Gestión de Precios y Stock',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='incoming_stock',
            field=models.IntegerField(default=0, help_text='Stock comprado que aún no ha llegado a bodega.', verbose_name='Stock en Tránsito'),
        ),
    ]
