# Generated by Django 5.2 on 2026-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productpricing_product_incoming_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_combo',
            field=models.BooleanField(default=False, help_text='Marcar para evitar conteo doble en los reportes de inventario.', verbose_name='Es un Kit/Combo'),
        ),
    ]
